// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyVatLieuXayDung.Data;

#nullable disable

namespace QuanLyVatLieuXayDung.Migrations
{
    [DbContext(typeof(QLVLDbContext))]
    [Migration("20260320082711_KhoiTaoCSDL")]
    partial class KhoiTaoCSDL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChuHoaDon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhachHangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.HoaDon_ChiTiet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGiaBan")
                        .HasColumnType("int");

                    b.Property<int>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamID")
                        .HasColumnType("int");

                    b.Property<short>("SoLuongBan")
                        .HasColumnType("smallint");

                    b.Property<int>("VatLieuID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("VatLieuID");

                    b.ToTable("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.LoaiVatLieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LoaiVatLieu");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("QuyenHan")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.VatLieu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiVatLieuID")
                        .HasColumnType("int");

                    b.Property<int>("NhaCungCapID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenVatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiVatLieuID");

                    b.HasIndex("NhaCungCapID");

                    b.ToTable("VatLieu");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.HoaDon", b =>
                {
                    b.HasOne("QuanLyVatLieuXayDung.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDon")
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatLieuXayDung.Data.NhanVien", "NhanVien")
                        .WithMany("HoaDon")
                        .HasForeignKey("NhanVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.HoaDon_ChiTiet", b =>
                {
                    b.HasOne("QuanLyVatLieuXayDung.Data.HoaDon", "HoaDon")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatLieuXayDung.Data.VatLieu", "VatLieu")
                        .WithMany("HoaDon_ChiTiet")
                        .HasForeignKey("VatLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("VatLieu");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.VatLieu", b =>
                {
                    b.HasOne("QuanLyVatLieuXayDung.Data.LoaiVatLieu", "LoaiVatLieu")
                        .WithMany("VatLieu")
                        .HasForeignKey("LoaiVatLieuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatLieuXayDung.Data.NhaCungCap", "NhaCungCap")
                        .WithMany("VatLieu")
                        .HasForeignKey("NhaCungCapID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiVatLieu");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.HoaDon", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.KhachHang", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.LoaiVatLieu", b =>
                {
                    b.Navigation("VatLieu");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.NhaCungCap", b =>
                {
                    b.Navigation("VatLieu");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.NhanVien", b =>
                {
                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QuanLyVatLieuXayDung.Data.VatLieu", b =>
                {
                    b.Navigation("HoaDon_ChiTiet");
                });
#pragma warning restore 612, 618
        }
    }
}
